language: rust
sudo: false
dist: bionic
cache:
  apt: true
  cargo: true

addons:
  apt:
    packages:
      - libxcb-composite0-dev

rust:
  - nightly
  - beta
  - stable

script:
  - |
      cargo build &&
      cargo test &&
      cargo bench &&
      cargo doc
